-- ============================================================
-- OPTIMIZALO.APP - SEED EXTENDED (Vaciado por petición del usuario)
-- ============================================================
-- Las cuentas adicionales han sido eliminadas para dejar solo
-- la cuenta principal TechStore Pro (usuario 99).
